### ISSUE TITLE
Did not work none Quality Source select on stream

### ISSUE THREAD

**Issue by VariisHub** [saucettv/VideoAdBlockForTwitch#11]
Ads appear on stream that none Quality Source select

**Comment by VariisHub** [comment]
[https://upload.cc/i1/2021/08/02/9PxCpX.png](url)

**Comment by saucettv** [comment]
If you are seeing ads, you most likely have another extension or user-script that is over-riding this extension. Please check your other extensions, disable them all, except this one, then re-load the page. Then try to work out which extension is causing the issue. This extension is not compatible with other Twitch ad-blockers.
