### ISSUE TITLE
Video or stream autoplay after switching between tabs

### ISSUE THREAD

**Issue by serenadezzz** [saucettv/VideoAdBlockForTwitch#15]
If i pause a video, clip or stream on a tab, switch to another tab, the video, clip or stream autoplays on the background. No matter what i set on autoplay settings on firefox, it always autoplay the player in the background.

Tested on vanilla firefox with only this extension installed.

**Comment by Newtype14** [comment]
Can confirm I'm having the same problem. Also using Firefox. If you're watching a Twitch stream and switching to another tab, the stream reloads, regardless of whether it was playing or paused. Also, if you switch back to the Twitch tab, the stream reloads once again. Issue is not happening with the add-on disabled.

**Comment by saucettv** [comment]
Hi, please update to version 5.0.4, you can force update by going to about:addons , click on the cog icon and click Check For Updates. It was something I missed in version 5.0.3, but the new version is ready to be updated now. Thanks
