### ISSUE TITLE
[Firefox] Streams get unpaused when new tab is opened

### ISSUE THREAD

**Issue by Magicool-1** [saucettv/VideoAdBlockForTwitch#16]
# Description
When having Video Ad-Block, for Twitch-addon enabled steams will be unpaused when opening new tab.

# Steps to reproduce
1. Disable all addons besides Video Ad-Block, for Twitch
2. Open twitch stream
3. Pause the stream
4. Open new tab, either via bookmark, new tab icon or opening a link in new tab

# Additional Information
Video Ad-Block, for Twitch 5.0.3
Firefox 93.0b3 (64-Bit)
Windows 10 64bit 19043.1151

**Comment by saucettv** [comment]
Hi, this issue has been fixed in version 5.04, you should be able to force the update by going to about:addons and then click on the cog icon and click 'check for updates'. Thanks for reporting
