### ISSUE TITLE
Stream not pauseable

### ISSUE THREAD

**Issue by Avnsx** [saucettv/VideoAdBlockForTwitch#17]
Hey first of this is a great idea and extension, really appreciate that you develop this! 👍

Unfortunately I'm having an issue with pausing the twitch stream through my mouses media pause hotkey though. Everytime I pause the stream using the button the stream just automatically continues after a couple seconds instead. Only pausing the stream through the twitch media player works permanently.

Here's what I mean with Media Pause Hotkey 
![Banner](https://i.imgur.com/HdWjCwS.png)

**Comment by saucettv** [comment]
Hi, this might of been due to the pause bug that was fixed in version 5.1.1, could you please check that you are on that version of the extension? Thanks

**Comment by saucettv** [comment]
I will close this for now, but if this issue isn't fixed in version 5.1.1+, please comment and I can re-open it. Thanks

**Comment by Avnsx** [comment]
> Hi, this might of been due to the pause bug that was fixed in version 5.1.1, could you please check that you are on that version of the extension? Thanks

I'm using the chrome extension, which I downloaded yesterday. So whatever version that extension in the chrome store is, is the version I am using.

**Comment by saucettv** [comment]
Thanks, although I don't have the same mouse as you, I tried my own using the pause/play keybind and it seemed to work ok. Is there an option for stop/play? That might work better if there is.
