### ISSUE TITLE
Ads in Korean (non-English?) Streams

### ISSUE THREAD

**Issue by gitguest54** [saucettv/VideoAdBlockForTwitch#18]
I've recently noticed that ads do not get blocked in Korean streams for some reason. I'm not sure if it's for all non-English speaking streams but whenever I check out any Korean streamer, the ads get through. Not that big a deal for me since I don't watch non-English speaking streams, but it is something I noticed.

**Comment by saucettv** [comment]
Could you please confirm that you don't have TTV LOL or Purple Ad-Block installed? I'm trying a few now but not getting any ads at the moment, but will keep checking. If possible also share a stream that you see an ad in. Thanks

**Comment by saucettv** [comment]
You are right, just got an ad in a Korean stream. Will have to take a look into this. Thanks for letting me know!

**Comment by saucettv** [comment]
Fixed this in 5.1.2, will upload the new version now. f6fd977fc47c298b3bb670701ebcd3e4959f0a5c
