### ISSUE TITLE
Videos pausing

### ISSUE THREAD

**Issue by icgurney** [saucettv/VideoAdBlockForTwitch#25]
Twitch and YouTube video will pause every few seconds. Disabling this extension fixes the issue.

**Comment by saucettv** [comment]
Hi, this extension doesn't have the host permission for YouTube, so the extension doesn't run on YouTube at all. I'm not sure what the issue could be for you to be honest, but this extension won't affect YouTube, unless your issue is a bandwidth/buffering problem.

**Comment by icgurney** [comment]
I think maybe this is some other issue that just happened to stop when I disabled the extension.
