### ISSUE TITLE
quality keeps lowering when ads are getting blocked

### ISSUE THREAD

**Issue by ANaPhOrAX** [saucettv/VideoAdBlockForTwitch#27]
So basically, what the title says.. when ads are getting blocked, the quality of the stream gets lowered. but like, the quality setting won't change; it will still be set to (for example) source quality, except it clearly won't be source, it will be dogshit bitrate. Even manually switching off source quality to something else and then switching back doesn't (always) fix it.

**Comment by saucettv** [comment]
Hi, this is how the extension is supposed to work. We can only get an ad-free stream in 480p or less. So the add-on automatically transitions to the 480p ad-free stream, when it knows an ad is going to play. It then transitions back as soon as possible, usually 15 seconds.

If you are looking for full quality ad-free streams, you might have better luck with the proxy based extensions, however expect some downtime and buffering. https://github.com/pixeltris/TwitchAdSolutions

**Comment by ANaPhOrAX** [comment]
yeah but I'm saying it doesn't switch back as soon as possible. it used to, but not recently. recently it just stays trash quality until I manually fuck with it to get it back proper

**Comment by saucettv** [comment]
Oh ok, I will keep an eye out for it, I haven't noticed it personally, but sometimes they roll out updates to certain users only.

**Comment by saucettv** [comment]
I do know some advertisers, want the full ad length watched before it will return to original quality. So depending on the legnth of the ad, this could be over a minute.
