### ISSUE TITLE
Video freezes during ad now, audio keeps playing but video doesn't resume when ad finishes

### ISSUE THREAD

**Issue by robmonte** [saucettv/VideoAdBlockForTwitch#29]
Seems to be a new issue starting today (for me) Jan 17th.

**Comment by Gleamix** [comment]
Can confirm, happens to me aswell

**Comment by saucettv** [comment]
I have made a temp fix in version 5.2.5, the issue I think is trying to force the ad to finish early. So instead I have had to force 480p for the entire duration of the ad. I will keep looking for a better solution, but let me know if you still get the stuck issue. Thanks for reporting.

**Comment by datguypiko** [comment]
I disabled this extension and I still get freezes, stutters, loadings sometimes. Started happening recently. I think it could be Firefox or maybe uBlockOrigin.

**Comment by Gleamix** [comment]
works perfectly for me, thanks a lot !
