### ISSUE TITLE
Streams Not Loading, Infinite Looping (AdGuard Issue)

### ISSUE THREAD

**Issue by gitguest54** [saucettv/VideoAdBlockForTwitch#3]
Since yesterday Twitch has been acting weird with this extension enabled. It doesn't seem to load the streams anymore, it just shows a black loading screen that's looping. The only way to fix it is by disabling the extension. 

Yesterday, Twitch was having "issues" with the video playback which was giving a lot of users the "error #2000" screen that I was seeing with the TTV-LOL extension. I was not seeing this error message with your extension but I had a feeling Twitch was doing something to fix these adblockers, I don't know. But it all started happening after this https://twitter.com/TwitchSupport/status/1408491570886856709 yesterday. Is it me or is something going on?

**Comment by saucettv** [comment]
Hi,

Please try disabling all other extensions except this one and then see if you get the same issue. I've had lots of users reporting problems with AdGuard filtering interfering with this extension/Twitch and also having TTV LoL/Purple Ad-Block/UBlock user-scripts installed while also using this extension stops it from working.

Best way to test is to just disable every extension except this one, refresh the Twitch tab, or restart the browser and then check if you get the same issue. If you don't, re-enable the other extensions one by one, while also refreshing the Twitch tab to find the one causing the conflict, then keep it disabled.

If you do still get the issue after disabling all extensions except this one, let me know and we can try further steps. Please also let me know if you are on Firefox or Chrome.

I don't doubt that Twitch is already testing small changes, but this does seem to be isolated to a very small number of users, so I like to check the extensions conflicts first as it's an issue I can't reproduce no matter how hard I try, unless I install a conflicting extension.

For example one user said "When you turn on this program with AdGuard, the Twitch broadcast screen repeats loading only. I hope you solve this problem quickly." and after they investigated a little further they said "I couldn't solve it with the way I told you, but I solved it in a different way. It was to turn off AdGuard's traffic filtering."

I looked into it and AdGuard are trying some new blocking methods, what they are I don't know, but it actually blocks my extension, even though I don't use proxies. So it basically blocks the original Twitch request instead.

**Comment by gitguest54** [comment]
> Hi,
> 
> Please try disabling all other extensions except this one and then see if you get the same issue. I've had lots of users reporting problems with AdGuard filtering interfering with this extension/Twitch and also having TTV LoL/Purple Ad-Block/UBlock user-scripts installed while also using this extension stops it from working.
> 
> Best way to test is to just disable every extension except this one, refresh the Twitch tab, or restart the browser and then check if you get the same issue. If you don't, re-enable the other extensions one by one, while also refreshing the Twitch tab to find the one causing the conflict, then keep it disabled.
> 
> If you do still get the issue after disabling all extensions except this one, let me know and we can try further steps. Please also let me know if you are on Firefox or Chrome.
> 
> I don't doubt that Twitch is already testing small changes, but this does seem to be isolated to a very small number of users, so I like to check the extensions conflicts first as it's an issue I can't reproduce no matter how hard I try, unless I install a conflicting extension.
> 
> For example one user said "When you turn on this program with AdGuard, the Twitch broadcast screen repeats loading only. I hope you solve this problem quickly." and after they investigated a little further they said "I couldn't solve it with the way I told you, but I solved it in a different way. It was to turn off AdGuard's traffic filtering."
> 
> I looked into it and AdGuard are trying some new blocking methods, what they are I don't know, but it actually blocks my extension, even though I don't use proxies. So it basically blocks the original Twitch request instead.

Wow that was exactly the issue. I was able to pinpoint exactly which one it was (for me). In the Adguard app > Settings > Extensions, there's this option named "Adguard Extra" that I recently just enabled because I was getting pop ups and stuff in other sites so I was looking for a way to fix that. I unchecked it and your addon started working again. 
![HLUUyrwoUj](https://user-images.githubusercontent.com/75234274/123523953-3ace4580-d695-11eb-9b34-855024608cb4.png)

Thanks!

**Comment by saucettv** [comment]
Sweet! Think I'm going to have to contact AdGuard and find out why and how they are blocking my ad-blocker content script. Will keep this issue open for a while for other users. Thanks :)

**Comment by saucettv** [comment]
Ok so they have basically just copy pasted pixeltris's user-script into their own user-script and called it AdGuard Extra, creating a conflict. It's also the old Firefox version of the script, which is why it overides the new script.

If you want to still use it, click on the cog icon, then edit, then click the search icon and search for twitch. Then delete the line:
  'twitch.tv': '*://*.twitch.tv/*'

I'm going to contact them to show them the issue.

**Comment by gitguest54** [comment]
> Ok so they have basically just copy pasted pixeltris's user-script into their own user-script and called it AdGuard Extra, creating a conflict. It's also the old Firefox version of the script, which is why it overides the new script.
> 
> If you want to still use it, click on the cog icon, then edit, then click the search icon and search for twitch. Then delete the line:
> 'twitch.tv': '_://_.twitch.tv/*'
> 
> I'm going to contact them to show them the issue.

You're quick at helping out, thank you! This helped out. I can now have both enabled.

**Comment by saucettv** [comment]
No problem, only issue is, you might have to do that every time they update their script. Not sure how often they do this. Thanks again

**Comment by saucettv** [comment]
AdGuard's response has been great, they implemented a check function to stop the conflict in their beta version of their AdGuard Extra script. I will be implementing the same function to prevent future conflicts.
