### ISSUE TITLE
Stream not switching back to 1080p

### ISSUE THREAD

**Issue by gaekwad** [saucettv/VideoAdBlockForTwitch#31]
Since the newest update streams no longer automatically switch back to 1080p after switching to 480p for the ad.  I'm on Firefox 97.0.1

**Comment by NicotherZ** [comment]
Same for me

**Comment by saucettv** [comment]
I am just about to upload version 5.3.1. I cleaned up the code and fixed a few bugs that should stop the switching back issue as much as possible.

**Comment by funnelfactory** [comment]
This is still happening to me even on version 5.3.2. I load a stream, ads get blocked and the stream continues at 480p, then ads finish, the stream noticeably reloads (not sure what the technical description of this process is), and restarts at 480p, instead of the intended "source" quality.

**Comment by funnelfactory** [comment]
In addition to my previous comment, there are many streams that start at 480p, apparently don't go into ads mode, and remain at 480p. They show no signs of attempting to refresh/reload into "source" quality.
