### ISSUE TITLE
Waterfox Bug

### ISSUE THREAD

**Issue by Gevorian** [saucettv/VideoAdBlockForTwitch#33]
On Waterfox browser, when the extension changes from 1080p to 480p, it will sometimes get stuck on 480p and not revert to Auto. (May be an issue with Notify Track Changes in Theatre Mode option)

- Other extensions installed:
- Twitch Previews
- FFZ
- UBlock Origin

**Comment by FurkanVG** [comment]
This is also happening on my Firefox.
Also there is another thing which causes to put Streamers where i am subbed to 480p, and is getting stuck there with no auto switch.

**Comment by saucettv** [comment]
Hi, if you open lots of tabs at once and an ad shows on one of the first tabs opened, the player switches to 480p. So then the new tabs also switch to 480p. You can either wait for the first tab to finish it's blocking and revert to original quality, or manually change the other tabs quality.

I know this is a bug, but I just don't have time to work on it right now, sorry.

**Comment by saucettv** [comment]
https://github.com/saucettv/VideoAdBlockForTwitch/issues/32
