### ISSUE TITLE
Hide "Blocking Ads" message is not working

### ISSUE THREAD

**Issue by DavidBrazSan** [saucettv/VideoAdBlockForTwitch#35]
Even with the option enabled, the message still appears.
I tested it on Firefox.

**Comment by saucettv** [comment]
I'm unable to repeat this. I did have to refresh the page after selecting the hide option, but it's not showing on Firefox. Will keep the issue open though in case I notice it.

**Comment by saucettv** [comment]
Was this on a pre-roll or mid-roll?

**Comment by DavidBrazSan** [comment]
Ad block happens normally. the problem is that the ad block notification is not hidden.

It may have been some interference of some addons that I use.

These are the addons I use: ClearURLs, HTTPS Everywhere, LocalCDN, Privacy Badger, uBlock Origin.

**Comment by DavidBrazSan** [comment]
Even activated, it still appears.

![Sem título](https://user-images.githubusercontent.com/60136669/158025346-54562127-d57d-4822-a5ea-2465a7afb5e9.png)
