### ISSUE TITLE
Streams don't switch from 480p

### ISSUE THREAD

**Issue by LinkUK** [saucettv/VideoAdBlockForTwitch#36]
This has just started happening, for me, in the past few days. I can see a similar issue was closed recently, but it is still very much happening, so hope it was ok to make a new issue.

Streams start at 480p, ads are blocked, then the stream does 'the thing' where it usually snaps back to 'source' resolution but it gets stuck at 480p. Switching manually to the source resolution works fine after waiting for the ads to finish. Most, if not all streams now start in 480p regardless of whether they are trying to play ads or not, again manually switching back to the source resolution works immediately in this case. Another new thing is the small dialogue box that opens on stream where you can select the resolution opens by itself and wont go away until the plug-in does its thing.

This is on version 5.3.2 on Firefox 97.0.1 with no other Twitch related plug-ins installed

**Comment by Drehmini** [comment]
+1 I'm experiencing this on version 5.3.2 chrome 99.0.4844.51. 
Twitch related plugins are: FFZ and FFZ Addon Pack

This is even an issue on channels that I'm subbed to.

**Comment by funnelfactory** [comment]
Everything LinkUK has described is exactly what I've been experiencing for several days, now. Same versions as LinkUK and no other Twitch plugins installed, either.

**Comment by LinkUK** [comment]
My apologies, I didn't notice that there is another Open issue that sounds very similar, #32

**Comment by saucettv** [comment]
https://github.com/saucettv/VideoAdBlockForTwitch/issues/32
