### ISSUE TITLE
Add option to disable extension on clips page

### ISSUE THREAD

**Issue by ollikehy** [saucettv/VideoAdBlockForTwitch#37]
Whenever I open multiple tabs of clips (f.ex. from Reddit) they don't preload properly. Instead it shows an error message saying that the download was cancelled and I have to manually reload it. This is very annoying when you have multiple tabs of clips open. 

This error only occurs when this extension is enabled in the browser. I'm on Chrome Version 98.0.4758.102 and I have also have the uBlock-extension enabled.

The extension doesn't need to work on the clips-page, because as of now they don't support adds.  It would be nice to have the option to disable the extension on `clips.twitch.tv*` pages.

Error: 
![image](https://user-images.githubusercontent.com/22412060/156927476-469853c0-2200-43dd-a2a1-cdc70341a498.png)

**Comment by saucettv** [comment]
Hi, I can't reproduce this error. The script shouldn't affect the clips download as we only intercept the live weaver links only.
