### ISSUE TITLE
Getting Ads on Twitch again

### ISSUE THREAD

**Issue by John-Kryspin** [saucettv/VideoAdBlockForTwitch#4]
Hey looks like the extension is no longer working? Is it on my end or are you seeing the same behavior?

**Comment by saucettv** [comment]
Hi, if you haven't changed anything your end, please try uninstall/re-install of the extension plus a browser restart/tab refresh. There was an update on the 28th, it might be a cache issue and needs a refresh.

**Comment by saucettv** [comment]
Also please make sure that you don't have TTV LoL installed or Purple Ad-Block as they over-ride the extension.

**Comment by John-Kryspin** [comment]
Settings:
![image](https://user-images.githubusercontent.com/6597539/123946164-e82eab00-d96c-11eb-8113-94dcaa68211d.png)
Extensions:
![image](https://user-images.githubusercontent.com/6597539/123946226-f7adf400-d96c-11eb-8f5a-aff151396c6e.png)

What I am seeing:
![image](https://user-images.githubusercontent.com/6597539/123946258-00062f00-d96d-11eb-9420-21b3e6c40e92.png)

It seems to be intermittently not working. I'll let you know if I discover a common pattern.

**Comment by saucettv** [comment]
Your settings are fine, only thing I can think is it's another extension stopping the content script from being injected. I would first check your tamper monkey scripts and then ublock scripts (if you have any). I don't know if Chrome removes the content scripts on extension updates, but this does seem to happen each time I update, then after a browser restart/tab refresh it re-injects the content script.

This is a bit more complicated of a check, but would confirm if it's a new Twitch ad script that they are using or not. Right click on the Twitch web page when you get an ad, click inspect, then Network, then search for weaver in the search box. Click on the first few links that pop up, then click the Preview tab. Check if you see the word "twitch-stitched-ad" in the preview of one of them. If you don't, it might be an overlay type ad using a new script that we haven't blocked yet. If you do, then it's our script that is being blocked by another extension.

Could you let me know your country? I will try VPN there and test it.

**Comment by John-Kryspin** [comment]
County is USA.
I checked and inside the preview is this: CLASS="twitch-stitched-ad". So  I'll check tampermonkey and see if thats interacting poorly.

**Comment by John-Kryspin** [comment]
Yeah looks like my tampermonkey script is messing up this extension. Thanks for the help!

**Comment by saucettv** [comment]
No worries, thanks for working it out, if it happens again, feel free to open the issue again
