### ISSUE TITLE
Firefox addon problem

### ISSUE THREAD

**Issue by ClemGlacee** [saucettv/VideoAdBlockForTwitch#5]
https://i.gyazo.com/7331aa6043a76893515fc235045f567a.png

When trying to install

**Comment by ClemGlacee** [comment]
I can download any other extensions

**Comment by saucettv** [comment]
Hi, this is a new one for me, the add-on is hosted and distributed by Firefox, so we don't have control over where it downloads from.

The only thing I can think, is you have an extension or app that is blocking it for some reason. You can test this by opening Firefox in troubleshooting mode. Then try download the extension while in troubleshooting mode.

Here is the link on how to open Firefox in troubleshooting mode:

https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode?redirectslug=troubleshoot-firefox-issues-using-safe-mode&redirectlocale=en-US

Then to exit troubleshooting mode, click the top right menu and click exit, then restart the browser and see if the extension is now installed, is so, make sure it's enabled.

Let me know how you get on, thanks

**Comment by saucettv** [comment]
If the above does not work, this link has some more options to try https://www.thewindowsclub.com/add-on-could-not-be-downloaded-because-of-a-connection-failure

**Comment by saucettv** [comment]
Hopefully this fixed your issue, if not please reply and we can look further into it for you.
