### ISSUE TITLE
importScripts() failure

### ISSUE THREAD

**Issue by mscdex** [saucettv/VideoAdBlockForTwitch#8]
Just tonight I started getting:

```
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://usher.ttvnw.net/api/channel/hls/' failed to load.
```

as of c61985d7adc3184e994dce96d41ffd9b239dbd9b. It was working earlier today.

**Comment by saucettv** [comment]
Hi, this error is caused when the same or similar content script is being injected into the page, when there is already one there. We had problems with Adguard in the past, but they were supposed to of fixed it. It could also be a user-script in a user-script manager, if you have one. Please check your extensions, disable ones you think might be causing it, then refresh the page, do it one by one to work out the culprit. It's most likely a user-script if you have those. Let me know which one was causing it, if you could please.

If it's not any of them, it could possibly be that it injected the content script twice. Not sure why it would do this, but closing the tabs, clearing cache and re-opening the browser should fix it.

Thanks

**Comment by saucettv** [comment]
As an example, adguard use a similar script https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js .At the bottom of the page you will see a similar content script being injected.

**Comment by mscdex** [comment]
For some reason uBO was not clearing its cache of `userResourcesLocation`, so even though I removed the value and purged all caches, it was still there. Setting it to a dummy value instead (e.g. `file:///`) fixed the issue. Weird....
